### ISSUE TITLE
Create repository using quay:create-repository action

### ISSUE THREAD

**Issue by dmartinol** [rhdhorchestrator/workflow-software-templates#30]
https://www.npmjs.com/package/@janus-idp/backstage-scaffolder-backend-module-quay

example: https://github.com/janus-idp/backstage-plugins/blob/bba3dadfd1b0bbba709dcdfe02b19828e74413fe/plugins/quay-actions/examples/templates/01-quay-template.yaml

**Comment by ElaiShalevRH** [comment]
Hey, 
A PR addressing this issue was opened [here](https://github.com/parodos-dev/workflow-software-templates/pull/90).
