### ISSUE TITLE
Fix broken links in the template

### ISSUE THREAD

**Issue by masayag** [rhdhorchestrator/workflow-software-templates#97]
The template contains broken link in the techdoc section:
```
    - url: https://www.rhdhorchestrator.io/docs/core-concepts/workflow-types/
      title: Workflow Types
      icon: techdocs
```

this was introduced in the past since we moved to folder per version in the website doc repo.

this happens in several links, e.g. `scaffolder-templates/gitlab-workflows/basic-workflow/template.yaml`

**Comment by ElaiShalevRH** [comment]
A PR has been opened to fix this issue:
https://github.com/rhdhorchestrator/workflow-software-templates/pull/98
